version: 2
jobs:
  python-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          command: |
            python -m unittest
workflows:
  version: 2
  some-test:
    jobs:
      - python-test