version: 2
jobs:
  python-test:
    docker:
      - image: cimg/python:3.10.4
    parallelism: 1
    steps:
      - when:
          condition: 
            equal: [ 'check', << `date +”%a”` >> ]
          steps:
            - run: echo "ok"
workflows:
  version: 2
  some-test:
    jobs:
      - python-test